BromineTech/BromineTech

- server/.gitignore
- server/index.js
- server/package-lock.json
- server/package.json
Setup of auth0 authentication is done in a VC by Gitesh and Rajeev.
> auth setup

- server/index.js
added http route handler skeletons for all the routes
> add route handler skeletons

- server/auth0Config.js
- server/dbConfig.js
- server/index.js
- server/middlewares/insertIntoUser.js
- server/package-lock.json
- server/package.json
> SQL queries for API done

- server/utils/randomString.js
> ulits added

- server/routes/index.js
- server/routes/project.js
dns initialised / create project
> dns initialised

- server/middlewares/getDbId.js
- server/middlewares/insertIntoUser.js
- server/routes/index.js
- server/routes/project.js
> DNS established

- server/package-lock.json
- server/package.json
- server/routes/index.js
- server/routes/profile.js
- server/routes/project.js
used useplunk for email service
> email setup done

- server/app.js
- server/package-lock.json
- server/package.json
- server/routes/index.js
- server/routes/project.js
- server/websockets/socket.js
> wss setup done

- server/app.js
- server/routes/project.js
- server/websockets/socket.js
routes setup done for websockets
Routes are as follows
/project/:projectid/overview
/project/:projectid/issues
/project/:projectid/:issueid
> routes setup done for websockets

- client/app/waitlist/page.tsx
> minor ui fixes

- server/routes/profile.js
- server/routes/project.js
finalized the email template after testing it thoroughly
> invite email modified

- server/routes/project.js
the server was sending "Invite Sent" even when the email was not sent. 
this error is resolved in this fix
> add member error resolved

- server/routes/project.js
> updated member role

- server/package-lock.json
- server/package.json
- server/routes/project.js
zod done for addMember route and updateMemberRole route
> zod done for addMember route and updateMemberRole route

- server/dbConfig.js
- server/routes/project.js
- server/utils/messageObject.js
- server/websockets/socket.js
ws server sql pool connection logic done, msg  object for websocket finalised.
> ws server, sql pool connection, mesage object finalised

- server/routes/project.js
- server/utils/messageObject.js
- server/websockets/socket.js
ws if condition for each dbquery is initialised
> ws if condition for each dbquery is initialised

- server/websockets/socket.js
gave structure to if blocks for sql queries in ws
> gave structure to if blocks for sql queries in ws

- server/websockets/socket.js
added some queries in switch statements of ws
> added some queries in switch statements of ws

- server/websockets/socket.js
> some minor changes

- client/components/placeholdersvanishandinput.tsx
> light mode fix

- client/app/page.tsx
- client/components/Button.tsx
- client/components/Navbar.tsx
- client/components/PopUpEmail.tsx
- client/components/PropertiesSidebar.tsx
- client/components/Sidebar.tsx
- client/package-lock.json
- client/package.json
- client/postcss.config.js
- client/tailwind.config.ts
- types/index.d.ts
- types/properties.ts
. Navbar
. Sidebar
. PropertiesSidebar
. Popup Email Modal
> frontend components initiated
